stages:
  data_ingestion:
    cmd: python src/wineQualityPre/pipeline/stage_01_data_ingestion.py
    deps:
      - src/wineQualityPre/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/winequality-red.csv

  data_validation:
    cmd: python src/wineQualityPre/pipeline/stage_02_data_validation.py
    deps:
      - src/wineQualityPre/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/winequality-red.csv
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/wineQualityPre/pipeline/stage_03_data_transformation.py
    deps:
      - src/wineQualityPre/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/winequality-red.csv
      - artifacts/data_validation/status.txt
    outs:
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv

  model_training:
    cmd: python src/wineQualityPre/pipeline/stage_04_model_trainer.py
    deps:
      - src/wineQualityPre/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    params:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python src/wineQualityPre/pipeline/stage_05_model_evaluation.py
    deps:
      - src/wineQualityPre/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/model_trainer/model.joblib
      - artifacts/data_transformation/test.csv
