stages:
  data_ingestion:
    cmd: python src/wineQualityPre/pipeline/stage_01_data_ingestion.py
    deps:
      - src/wineQualityPre/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/winequality-red.csv
